In [8]:
import pandas as pd
import numpy as np
import sqlite3

In [9]:
# Set SQL connection - you need to download the sqlite file from Kaggle
conn = sqlite3.connect("database.sqlite")

# Get column names
loan_col = np.array(pd.read_sql_query("select * from loan limit 1;", conn).columns)

In [10]:
# Iterate through all columns and create summary - take around five minutes to run
loan_summary = pd.DataFrame()

for col in loan_col:
    
    try:
        df = pd.read_sql_query("Select "+ col + " from loan;", conn).replace(r'^\s*$', np.nan, regex=True).dropna().astype("float").describe()
        loan_summary = pd.concat([loan_summary,df],axis=1)
    except: 
        continue

In [13]:
loan_summary

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,revol_bal,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,policy_code
count,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2260668.0
mean,1.504693e+04,1.504166e+04,1.502344e+04,1.309291e+01,4.458076e+02,1.665846e+04,4.446293e+03,4.445295e+03,1.182403e+04,1.180594e+04,9.300142e+03,2.386352e+03,1.462469e+00,1.360740e+02,2.259328e+01,3.364015e+03,1.0
std,9.190245e+03,9.188413e+03,9.192332e+03,4.832114e+00,2.671737e+02,2.294831e+04,7.547612e+03,7.546657e+03,9.889599e+03,9.884835e+03,8.304886e+03,2.663086e+03,1.150210e+01,7.258317e+02,1.271114e+02,5.971757e+03,0.0
min,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-9.500000e-09,0.000000e+00,0.000000e+00,0.000000e+00,1.0
25%,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,5.950000e+03,0.000000e+00,0.000000e+00,4.272580e+03,4.257730e+03,2.846180e+03,6.936100e+02,0.000000e+00,0.000000e+00,0.000000e+00,3.086400e+02,1.0
50%,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,1.132400e+04,0.000000e+00,0.000000e+00,9.060870e+03,9.043080e+03,6.823385e+03,1.485280e+03,0.000000e+00,0.000000e+00,0.000000e+00,5.884700e+02,1.0
75%,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,2.024600e+04,6.712632e+03,6.710320e+03,1.670797e+04,1.668257e+04,1.339750e+04,3.052220e+03,0.000000e+00,0.000000e+00,0.000000e+00,3.534965e+03,1.0
max,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,2.904836e+06,4.000000e+04,4.000000e+04,6.329688e+04,6.329688e+04,4.000000e+04,2.819250e+04,1.427250e+03,3.985955e+04,7.174719e+03,4.219205e+04,1.0